#! /bin/bash

if hyprctl monitors | sed -n '/eDP-1/,/disabled/p' | grep 'disabled: false'; then
  hyprctl keyword monitor "eDP-1, disable"
else
  hyprctl keyword monitor "eDP-1,1920x1200@60,auto-down,1"
fi

