[[mgr.prepend_keymap]]
on = "!"
run = 'shell "$SHELL" --block'
desc = "Open shell here"

[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input or quit yazi"


[[mgr.prepend_keymap]]
on = "n"
run = "create"
desc = "Create a new file or directory"

[[mgr.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Close tab or the process if only 1 tab"


[[mgr.prepend_keymap]]
on = ["f", "f"]
run = ["cd ~", "plugin fzf"]
desc = "Search for files or directories with fzf"

[[mgr.prepend_keymap]]
on = "D"
run = "remove --permanently"
desc = "Remove a file or directory permenently"

[[mgr.prepend_keymap]]
on = ["c", "a"]
run = ["plugin copy-file-contents"]
desc = "Copy file contents"

[[mgr.prepend_keymap]]
on = ["f", "g"]
run = "search --via=rga"
desc = "Grep through files"

[[mgr.prepend_keymap]]
on = "e"
run = "plugin eza-preview"
desc = "Toggle tree/list directory preview"

[[mgr.prepend_keymap]]
on = "o"
run = "plugin open-with-cmd block"
desc = "Open with command in the terminal"

[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin bypass smart-enter"
desc = "Open a file or recursively enter child directory, skipping children with only a single subdirectory"

[[mgr.prepend_keymap]]
on = "`"
run = "plugin bunny"
desc = "Start bunny.yazi"

[[mgr.prepend_keymap]]
on = "<C-Space>"
run = "toggle_all --state=off"
desc = "Deselect any selection"

[[mgr.prepend_keymap]]
on = "z"
run = "plugin zoxide"
desc = "Look at zoxide database"

[[mgr.prepend_keymap]]
on = ["l", "g"]
run = "plugin lazygit"
desc = "run lazygit"
