[manager]
sort_by = "alphabetical"
show_symlink = false
mouse_events = ["click", "scroll", "move", "drag"]
ratio = [2, 2, 5]

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
  { mime = "image/*", run = "image" },
  { name = "*.pdf", run = "pdf" },
  { name = "*/", run = "eza-preview" },
  { mime = "text/*", run = "bat" },
]


[preview]
wrap = "yes"

[opener]
edit = [{ run = '/usr/bin/nvim "$@"', block = true, for = "unix" }]
